name: gym_tracker_ui
description: "Gym Progress Tracker Demo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_calendar_week: ^3.0.3
  intl: ^0.19.0
  table_calendar: ^3.1.3
  google_fonts: ^6.2.0
  fl_chart: ^1.1.0
  percent_indicator: ^4.2.5
  just_audio: ^0.10.5
  alarm: ^5.1.5
  permission_handler: ^12.0.1
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sounds/timer_sounds/

  uses-material-design: true