import 'package:gym_tracker_ui/domain/entitites/excercise_blueprint.dart';

const dummyExcercisesBlueprints = [
  ExcerciseBlueprint(
    name: "Barbell Bench Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dumbbell Bench Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Incline Barbell Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Incline Dumbbell Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Decline Barbell Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Decline Dumbbell Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dumbbell Pullover",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Chest Press Machine",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Pec Deck",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Cable Fly",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Smith Machine Bench Press",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Push-ups",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dips (Chest Focus)",
    category: ExcerciseCategory.chest,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Deadlift",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 5,
    recommendedMaxNumberOfReps: 8,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Barbell Bent-over Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dumbbell Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "T-Bar Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Pendlay Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 8,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Lat Pulldown",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Seated Cable Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Machine Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Hammer Strength High Row",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Cable Pullover",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Pull-ups",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Chin-ups",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Inverted Rows",
    category: ExcerciseCategory.back,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Barbell Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dumbbell Alternating Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Incline Dumbbell Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Preacher Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Concentration Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Cable Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Hammer Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Zottman Curl",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Close-grip Bench Press",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Tricep Dips",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Skull Crushers",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Overhead Triceps Extension",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Rope Pushdowns",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Straight Bar Pushdowns",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Kickbacks",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Wrist Curls",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 12,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Reverse Curls",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Farmer’s Carries",
    category: ExcerciseCategory.arms,
    recommendedMinNumberOfReps: 30,
    recommendedMaxNumberOfReps: 60,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Overhead Press",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Dumbbell Shoulder Press",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Arnold Press",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Lateral Raise",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Front Raise",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Rear Delt Fly",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Shrugs",
    category: ExcerciseCategory.shoulders,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Back Squat",
    category: ExcerciseCategory.quads,
    recommendedMinNumberOfReps: 5,
    recommendedMaxNumberOfReps: 8,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Front Squat",
    category: ExcerciseCategory.quads,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Leg Press",
    category: ExcerciseCategory.quads,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Lunges",
    category: ExcerciseCategory.quads,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Leg Extension",
    category: ExcerciseCategory.quads,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Romanian Deadlift",
    category: ExcerciseCategory.hamstrings,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Stiff-Leg Deadlift",
    category: ExcerciseCategory.hamstrings,
    recommendedMinNumberOfReps: 6,
    recommendedMaxNumberOfReps: 10,
    recommendedRestTime: Duration(minutes: 3, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Leg Curl Machine",
    category: ExcerciseCategory.hamstrings,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Hip Thrust",
    category: ExcerciseCategory.glutes,
    recommendedMinNumberOfReps: 8,
    recommendedMaxNumberOfReps: 12,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Glute Bridge",
    category: ExcerciseCategory.glutes,
    recommendedMinNumberOfReps: 10,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Cable Kickbacks",
    category: ExcerciseCategory.glutes,
    recommendedMinNumberOfReps: 12,
    recommendedMaxNumberOfReps: 15,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Standing Calf Raise",
    category: ExcerciseCategory.calves,
    recommendedMinNumberOfReps: 12,
    recommendedMaxNumberOfReps: 20,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Seated Calf Raise",
    category: ExcerciseCategory.calves,
    recommendedMinNumberOfReps: 12,
    recommendedMaxNumberOfReps: 20,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Crunches",
    category: ExcerciseCategory.abs,
    recommendedMinNumberOfReps: 15,
    recommendedMaxNumberOfReps: 25,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Leg Raises",
    category: ExcerciseCategory.abs,
    recommendedMinNumberOfReps: 12,
    recommendedMaxNumberOfReps: 20,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
  ExcerciseBlueprint(
    name: "Plank",
    category: ExcerciseCategory.abs,
    recommendedMinNumberOfReps: 30,
    recommendedMaxNumberOfReps: 60,
    recommendedRestTime: Duration(minutes: 1, seconds: 30),
  ),
];
